# Experiment settings

MIN_CARDINALITY = 2
MAX_CARDINALITY = 5
EVIDENCE_CARDINALITY = 2
ABSTRACT_CARDINALITY = 5
NUM_NODES = 30
NUM_ITERS = 200
MIN_NUM_EVIDENCE_NODES = NUM_NODES // 5
MAX_NUM_EVIDENCE_NODES = NUM_NODES // 5
MIN_NUM_ABSTRACTED_NODES = 5
MAX_NUM_ABSTRACTED_NODES = 5

NUM_EXAMPLES = 100*(EVIDENCE_CARDINALITY**MAX_NUM_EVIDENCE_NODES) 
#NUM_EXAMPLES = EVIDENCE_CARDINALITY**MAX_NUM_EVIDENCE_NODES

DETERMINISTIC_CPTS = True
USE_FIXED_THRESHOLDS = True
USE_ASCEND_THRESHOLDS = True
FIXED_REGULAR_CPTS = False
SELECT_CPT_TYPE = 'sigmoid'
USE_NODE_V2 = True
NUM_INTERVALS = 3

SEED = 1024
intervals_list = [2,4,6,8]
intervals_hand_list = [2,4,6]
intervals_learn_list = [2,4,6,8,10,12,14,16,18]
evidence_size_list = [4,5,6,7,8]
NUM_TRIALS = 2
NUM_FIT_TRIALS = 1

NUM_WORKERS = 10