# Experiment settings

MIN_CARDINALITY = 2
MAX_CARDINALITY = 5
EVIDENCE_CARDINALITY = 2
ABSTRACT_CARDINALITY = 5
NUM_NODES = 40
NUM_ITERS = 50
MIN_NUM_EVIDENCE_NODES = NUM_NODES//5
MAX_NUM_EVIDENCE_NODES = NUM_NODES//5
MIN_NUM_ABSTRACTED_NODES = NUM_NODES//5
MAX_NUM_ABSTRACTED_NODES = NUM_NODES//5

NUM_EXAMPLES = 100*(EVIDENCE_CARDINALITY**MAX_NUM_EVIDENCE_NODES) 
#NUM_EXAMPLES = EVIDENCE_CARDINALITY**MAX_NUM_EVIDENCE_NODES

DETERMINISTIC_CPTS = True
USE_FIXED_THRESHOLDS = False
USE_ASCEND_THRESHOLDS = True
FIXED_REGULAR_CPTS = False
SELECT_CPT_TYPE = 'sigmoid'
USE_NODE_V2 = True
NUM_INTERVALS = 3

intervals_list = [2,10,20,30,40,50]
NUM_TRIALS = 20
NUM_FIT_TRIALS = 1

NUM_WORKERS = 5