# Experiment settings

MIN_CARDINALITY = 2
MAX_CARDINALITY = 5
EVIDENCE_CARDINALITY = 3
ABSTRACT_CARDINALITY = 5
NUM_NODES = 10
NUM_ITERS = 500
MIN_NUM_EVIDENCE_NODES = NUM_NODES//5
MAX_NUM_EVIDENCE_NODES = NUM_NODES//5
MIN_NUM_ABSTRACTED_NODES = NUM_NODES//3

NUM_EXAMPLES = 100*(EVIDENCE_CARDINALITY**MAX_NUM_EVIDENCE_NODES) 

DETERMINISTIC_CPTS = True
USE_FIXED_THRESHOLDS = False
FIXED_REGULAR_CPTS = True
#DETERMINISTIC_CPTS = True
SELECT_CPT_TYPE = 'nearest'
USE_NODE_V2 = True
NUM_INTERVALS = 3

intervals_list = [2,3,4,5,6,7,8,9,10]
NUM_TRIALS = 1
NUM_FIT_TRIALS = 3